### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ghost** [JadedPacks/Magic-Farm#1]
- [ ] Check all configs
- [ ] Rewrite MT scripts?
- [ ] Make sure it still loads?
- [ ] Add JadedMenu (and other jaded mods?)
- [ ] Give love!
